### ISSUE TITLE
[질문] 모듈 설치 과정중 오류(윈도우 버전)

### ISSUE THREAD

**Issue by audrb1999** [HyungjinLee/POSCO_B3#1]
초반에 requirements 를 install하는데 pycurl과 pyrhon-apt + ubuntu 에서 오류가 발생했습니다. pycurl 같은 경우에는 윈도우 버전을 따로 다운받아 가상공간 lib에 넣어서 해결했는데 python-apt + ubuntu같은 경우에는 구글링해도 못찾겠습니다..

해결할 수 있는 방법이 있나요??

**Comment by HyungjinLee** [comment]
안녕하세요.

에러메시지를 더 자세히 올려주시면 답변이 가능할 수도 있을 것 같네요 : )

**Comment by audrb1999** [comment]
앗 .. 답변해주셔서 정말 감사합니다 ㅜㅠ

문제가 생긴 모듈들 입니다
argon2-cffi==20.1.0
bleach==1.5.0
grpcio==1.31.0
html5lib==0.9999999
jsonschema==3.2.0
pycurl==7.43.0
pygobject==3.20.0  
python-apt==1.1.0b1+ubuntu0.16.4.9
six==1.10.0
unattended-upgrades==0.1




1. 오류
ERROR: Could not find a version that satisfies the requirement (모듈)
ERROR: No matching distribution found for (모듈)


    1. pygobject==3.20.0 > 오류 때문에 버전을 지웠습니다> pygobject

    2. python-apt==1.1.0b1+ubuntu0.16.4.    > 이것도 버전을 지웠습니다

    3. unattended-upgrades==0.1  > 버전을 지워도 똑같은 오류 발생했습니다 
        그래서 일단 제외하고 다른 모듈부터 돌렸습니다



2. 오류
ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 16), -r require
ments.txt (line 6), argon2-cffi==20.1.0, html5lib==0.9999999, jsonschema==3.2.0 and six==1.10
.0 because these package versions have conflicting dependencies.


나온 모듈 버전을 지웠습니다





그 이후에


    ERROR: Command errored out with exit status 1:
 

  ERROR: Command errored out with exit status 1:
  
  ERROR: Failed building wheel for python-apt
  Running setup.py clean for python-apt
Failed to build pygobject python-apt
ERROR: Could not build wheels for pygobject which use PEP 517 and cannot be installed directly


이렇게 오류가 뜨면서 진행이 안됩니다...

**Comment by audrb1999** [comment]
윈도우에서 콘다로 가상환경 만들어서 주피터 랩에서 진행햇고 파이썬 버전은 3.6.12 텐서플로는 1.8.0 입니다!

**Comment by HyungjinLee** [comment]
답변이 늦은 점 죄송합니다.

해당 프로젝트는 Ubuntu 16.04 환경과 GPU가 탑재되어있는 워크스테이션에서 진행하였고 깃에 commit 할 때 해당 컴퓨터의
개발환경이 requirements로 들어간 듯 합니다.
 따라서 윈도우 환경에서 진행하실 때 저 에러 메시지처럼 충돌이 난다면 *충돌 난 라이브러리를 제외하고 나머지만 설치하신 후 구글링을
통해 호환되는 환경을 만드시는 방법*이 좋겠네요.

리포지토리에 관심 가져 주셔서 감사드리구요, 추가적으로 궁금하신 사항 있으시다면 부담 없이 질문주세요~!!

2021년 2월 15일 (월) 오후 5:32, audrb1999 <notifications@github.com>님이 작성:

**Comment by audrb1999** [comment]
이론 위주로 공부하다가 실제 코드를 돌릴려니 너무 힘드네요ㅜㅠ
답변해주셔서 정말 감사합니다!

**Comment by audrb1999** [comment]
궁금한 점이 있어서 질문드립니다.



1. 이 모델을 학습하면 노인분들도 예측할 수있나요?  아니면 39까지만 되는건가요?


---------------------------------------------------------------------------------------------


2. --data_dir /data/xdata/age-gender/aligned>  사진파일 저장 장소? > 이거 모든 사진을 한 곳을 모아야 하나요?
--output_dir /home/dpressel/dev/work/AgeGenderDeepLearning/Folds/tf/age_test_fold_is_0 > 모델 저장 장소?



이것도 AFAD_prepro랑 create_train_val_txt_files.ipynb 로 만들어지는 건가요? 
아니면 rude-carine나 AgeGenderDeepLearning 저장소에서 가져와야하는 건가요?

---------------------------------------------------------------------------------------------




읽어 주셔서 감사합니다!

**Comment by audrb1999** [comment]
아참  preproc파일에서
tf.app.flags.DEFINE_string('output_dir', '/home/dpressel/dev/work/AgeGenderDeepLearning/Folds/tf/test_fold_is_0',
                           'Output directory')

이거랑 
tf.app.flags.DEFINE_string('fold_dir', '/home/dpressel/dev/work/AgeGenderDeepLearning/Folds/train_val_txt_files_per_fold/test_fold_is_0',
                           'Fold directory')

이거 똑같은 test_fold_is_0 파일인데 경로가 서로 다른 이유가 있나요??

그리고 파이썬 명령어로 실행할 때
--output_dir /home/dpressel/dev/work/AgeGenderDeepLearning/Folds/tf/age_test_fold_is_0
이렇게 경로를 주던데 저 age_test_fold_is_0랑 test_fold_is_0 이름이 다른데 이유가 있는건가요?

**Comment by audrb1999** [comment]
$ python preproc.py --fold_dir /home/dpressel/dev/work/AgeGenderDeepLearning/Folds/train_val_txt_files_per_fold/test_fold_is_0 --train_list age_train.txt --valid_list age_val.txt --data_dir /data/xdata/age-gender/aligned --output_dir /home/dpressel/dev/work/AgeGenderDeepLearning/Folds/tf/age_test_fold_is_0

이 과정을

--data_dir을 AFAD-Full 경로로 설정하고
--output_dir은 저장장소라고 생각해서 폴더하나 새로만들어서 지정했습니다.

----------------------------------------------------------------------------
실행결과
2021-03-16 16:40:51.805944 [thread 0]: Wrote 8232 images to 8232 shards.
2021-03-16 16:40:52.679915: Finished writing all 16465 images in data set.

마지막에 이렇게 출력되고

train-00003-of-00010 이런 파일들이 생겨서 이 경로를 --train_dir
로 줘서 train.py를 실행시켰는데 loss값이 0.580~0.700 구간을 진동하기만 하고 뭔가 변화가 없네요 ㅠㅜ 뭔갈 잘못한거 같은데...
